import assert from 'node:assert/strict';
import {marketStreamManager as manager} from '../server/services/marketStreamService';
const m=manager as any;
m.startUpstreamStream=()=>{};
const symbol='OANDA:XAUUSD';
manager.subscribeSymbol(symbol,symbol);
const sub=m.subscriptions.get(symbol);
const start=Math.floor((Date.now()-600000)/300000)*300;
const seed={time:start,open:2300,high:2301,low:2299,close:2300,volume:10};
manager.updateLiveCandleInCache(symbol,'5',seed);
let observations=0;const un=manager.onFiveMinuteBar(()=>observations++);
const tick=(time:number,price:number)=>m.handleIncomingTick(sub,{symbol,time,price,source:'test'});
tick(start+10,2302);tick(start+10,2302);
assert.equal(observations,1,'duplicate quote delivery is evaluated once');
manager.updateLiveCandleInCache(symbol,'5',{...seed,close:2290});
assert.equal(manager.getCurrentBar(symbol,'5')!.close,2302,'late history cannot overwrite live close');
tick(start+300,2303);tick(start+301,2304);
assert.deepEqual(manager.getCurrentBar(symbol,'5'),{time:start+300,open:2303,high:2304,low:2303,close:2304,volume:0});
tick(start+290,2200);assert.equal(manager.getCurrentBar(symbol,'5')!.close,2304,'old tick cannot alter current candle');
tick(start+600,2305);
const merged=manager.mergeCurrentBars(symbol,'5',[seed]);
assert.deepEqual(merged.map(c=>c.time),[start,start+300,start+600],'joining from old history receives intervening canonical candles');
assert.equal(merged[1].open,2303,'late join sees original open, not joining price');
un();console.log('PASS canonical buckets, duplicate/stale ticks, delayed history, missing cached bars and identical late-join open');
